import { StyleSheet } from 'react-native';
import { colors, radii, spacing, typography } from '../../theme/tokens';

export const adminStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: 'transparent' },
  scroll: { paddingBottom: spacing.xxl },
  headerRow: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.md, marginBottom: spacing.xl },
  screenHeading: { flex: 1 },
  tabScroller: { marginBottom: spacing.lg },
  tabRow: { flexDirection: 'row', gap: spacing.sm, paddingRight: spacing.md },
  tabChip: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: radii.pill,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.surfaceBorder,
  },
  tabChipActive: { backgroundColor: colors.surfaceElevated, borderColor: colors.surfaceBorderStrong },
  tabLabel: { ...typography.caption, fontSize: 12, color: colors.textMuted },
  tabLabelActive: { color: colors.cyan, fontFamily: 'Sora_500Medium' },
  sectionTitle: {
    ...typography.title,
    fontSize: 17,
    lineHeight: 23,
    color: colors.textPrimary,
  },
  sectionHeader: {
    marginTop: spacing.lg,
    marginBottom: spacing.sm,
  },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  statTile: { flexGrow: 1, flexBasis: 150, borderRadius: radii.lg },
  statTileInner: { padding: spacing.md, gap: 2 },
  statValue: { ...typography.title, fontSize: 22, color: colors.textPrimary, fontVariant: ['tabular-nums'] },
  statLabel: { ...typography.caption, color: colors.textMuted },
  panel: { borderRadius: radii.lg },
  panelBody: { padding: spacing.lg, gap: spacing.md },
  fieldRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.md },
  fieldLabel: { ...typography.body, color: colors.textMuted },
  fieldValue: { ...typography.subtitle, fontSize: 15, color: colors.textPrimary, fontVariant: ['tabular-nums'] },
  mutedLine: { ...typography.caption, color: colors.textMuted },
  loadingState: { minHeight: 180, alignItems: 'center', justifyContent: 'center', gap: spacing.md },
  sectionError: {
    marginBottom: spacing.md,
    padding: spacing.md,
    gap: spacing.sm,
    borderRadius: radii.md,
    backgroundColor: colors.surfaceElevated,
    borderWidth: 1,
    borderColor: colors.danger,
  },
  sectionErrorTitle: { ...typography.subtitle, fontSize: 14, color: colors.danger },
  sectionErrorRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.md },
  sectionErrorCopy: { ...typography.caption, flex: 1, color: colors.textSecondary },
  retryButton: { minHeight: 44, paddingVertical: spacing.sm },
  controlsPanel: {
    gap: spacing.md,
    padding: spacing.md,
    marginBottom: spacing.md,
    borderRadius: radii.lg,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.surfaceBorder,
  },
  searchRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  searchInputWrap: {
    minHeight: 48,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: radii.md,
    backgroundColor: colors.surfaceBright,
    borderWidth: 1,
    borderColor: colors.surfaceBorder,
  },
  searchInput: { ...typography.body, flex: 1, minWidth: 0, color: colors.textPrimary, paddingVertical: spacing.sm },
  searchButton: { minHeight: 48, paddingVertical: spacing.sm, paddingHorizontal: spacing.md },
  controlGroup: { gap: spacing.sm },
  controlLabel: { ...typography.caption, color: colors.textMuted },
  controlChips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  controlChip: {
    minHeight: 40,
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceBright,
    borderWidth: 1,
    borderColor: colors.surfaceBorder,
  },
  controlChipActive: { backgroundColor: colors.surfaceElevated, borderColor: colors.surfaceBorderStrong },
  controlChipLabel: { ...typography.caption, color: colors.textMuted },
  controlChipLabelActive: { color: colors.cyan, fontFamily: 'Sora_500Medium' },
  pagingFooter: { alignItems: 'center', gap: spacing.sm, paddingVertical: spacing.lg },
  pagingLabel: { ...typography.caption, color: colors.textMuted, fontVariant: ['tabular-nums'] },
  loadMoreButton: { minWidth: 180, minHeight: 44, paddingVertical: spacing.sm },
  sparkRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 3, height: 60 },
  sparkBarTrack: { flex: 1, height: '100%', justifyContent: 'flex-end' },
  sparkBar: { width: '100%', borderRadius: 2, backgroundColor: colors.cyan, minHeight: 4 },
  list: { gap: spacing.sm },
  row: { borderRadius: radii.lg },
  rowContent: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, padding: spacing.md },
  badge: {
    width: 40,
    height: 40,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceElevated,
    borderWidth: 1,
    borderColor: colors.surfaceBorder,
  },
  badgeFailed: { borderColor: colors.danger },
  badgeOpen: { borderColor: colors.cyan },
  title: { ...typography.subtitle, fontSize: 15, color: colors.textPrimary },
  subtitle: { ...typography.caption, color: colors.textSecondary },
  barRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  barLabel: { ...typography.caption, color: colors.textMuted, width: 90 },
  barTrack: { flex: 1, height: 10, borderRadius: 5, backgroundColor: colors.surfaceBright, overflow: 'hidden' },
  barFill: { height: '100%', borderRadius: 5, minWidth: 4 },
  barValue: { ...typography.caption, color: colors.textPrimary, width: 28, textAlign: 'right', fontVariant: ['tabular-nums'] },
  adminBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: radii.sm,
    backgroundColor: colors.surfaceElevated,
    borderWidth: 1,
    borderColor: colors.surfaceBorderStrong,
  },
  adminBadgeLabel: { ...typography.caption, fontSize: 9, letterSpacing: 1, color: colors.cyan },
  emailInput: {
    ...typography.body,
    minHeight: 44,
    color: colors.textPrimary,
    backgroundColor: colors.surfaceBright,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.surfaceBorder,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  emailEditButton: { minHeight: 44, justifyContent: 'center' },
  emailEditor: { gap: spacing.sm },
  emailActions: { flexDirection: 'row', gap: spacing.sm },
  inlineButton: { minHeight: 40, paddingVertical: spacing.xs, paddingHorizontal: spacing.md },
  fieldError: { ...typography.caption, color: colors.danger },
  acknowledgement: { ...typography.caption, color: colors.success },
  roleButton: {
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceBright,
    borderWidth: 1,
    borderColor: colors.surfaceBorder,
  },
  roleButtonActive: { backgroundColor: colors.surfaceElevated, borderColor: colors.surfaceBorderStrong },
  roleButtonLabel: { ...typography.caption, color: colors.textSecondary },
  roleButtonLabelActive: { ...typography.caption, color: colors.cyan },
  feedbackMessage: { ...typography.body, color: colors.textPrimary },
  replyButton: { minWidth: 112 },
  confirmTitle: { ...typography.title, fontSize: 18, color: colors.textPrimary },
  confirmBody: { ...typography.body, color: colors.textSecondary },
  confirmEmail: { ...typography.subtitle, color: colors.textPrimary },
  confirmActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: spacing.sm, marginTop: spacing.md },
  confirmButton: { minHeight: 46, paddingVertical: spacing.sm },
  inlineSectionTitle: { ...typography.subtitle, fontSize: 16, lineHeight: 22 },
  announcementBody: { minHeight: 96, textAlignVertical: 'top' },
  postButton: { marginTop: spacing.xs },
});
